BOARD      = CROONER_2_0
TARGET     = flac_test
BASE       = ../..

SOURCES = \
    main.c

LIBRARIES = \
    media-flac \
    efsl \
    bsp \
    util \
    linked-list

include $(BASE)/apps/make/Makefile.common
