BOARD      = CROONER_2_0
TARGET     = asm_test
BASE       = ../..

SOURCES = \
    main.c \
    avr32.S

LIBRARIES = bsp

STACK_SIZE = 48K

OPTIMIZATIONS = -O3

include $(BASE)/apps/make/Makefile.common
