BOARD      = CROONER_2_0
TARGET     = verify
BASE       = ../..

SOURCES = \
          abdac.c \
          main.c

LIBRARIES = \
            linked-list \
            led \
            freertos \
            bsp \
            util

include Makefile.common
