BOARD      = CROONER_2_0
TARGET     = cd_changer
BASE       = ../..

SOURCES = \
          ibus.c \
          blu.c \
          playback.c \
          main.c

LIBRARIES = \
            freertos \
            efsl \
            media-interface \
            media-flac \
            file-stream \
            linked-list \
            display \
            bsp \
            util

OPTIMIZATIONS = -O0

include $(BASE)/apps/make/Makefile.common
